CREATE TABLE `data` (
	`id` integer PRIMARY KEY NOT NULL,
	`kbi` text NOT NULL,
	`image` text,
	`tanggal` text NOT NULL,
	`kejadian` text NOT NULL,
	`kategori` text NOT NULL,
	`lokasi` text NOT NULL,
	`posisi` text NOT NULL,
	`sumber` text NOT NULL,
	`petugas` text NOT NULL,
	`barcode` text,
	`keterangan` text NOT NULL,
	`penyebab` text NOT NULL,
	`kronologi` text NOT NULL,
	`upaya` text NOT NULL,
	`wilayah_terdampak` text NOT NULL,
	`korban_jiwa` text NOT NULL,
	`kerusakan_infrastruktur` text,
	`kerusakan_lainnya` text NOT NULL,
	`multimedia` text,
	`status_tanggap_darurat` text NOT NULL,
	`berita_terkait` text NOT NULL,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP)
);
